package Projet;

/**
 * @author Bastien Canto bastien.canto@univ-tlse3.fr
 * @author Omar Kired omar.kired@univ-tlse3.fr
 * @author Bilel Besseghieur bilel.besseghieur@univ-tlse3.fr
 */

import javax.swing.JFrame;
import javax.swing.JTextField;
import java.awt.event.ActionEvent;

public class Fenetre extends javax.swing.JFrame {

    /**
     * Creates new form Fenetre
     */
    
    public Fenetre() {
        initComponents();
    }

    public static void fenetreStart() {
    	/* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Fenetre().setLocationRelativeTo(null); //permet de mettre la fenetre au mileu de l'ecran
            new Fenetre().setVisible(true); // pour rendre la fenetre visible
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        javax.swing.ButtonGroup buttonGroup_print = new javax.swing.ButtonGroup();
        jTabbedPane = new javax.swing.JTabbedPane();
        jPanel_config = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField_difficulte = new javax.swing.JTextField();
        jTextField_nbDiv = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_nbBlock = new javax.swing.JTextField();
        jTextField_nbUser = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField_recompence = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton_print_true = new javax.swing.JRadioButton();
        jRadioButton_print_false = new javax.swing.JRadioButton();
        jButton_start = new javax.swing.JButton();
        jButton_verifChain = new javax.swing.JButton();
        jButton_verifMerkel = new javax.swing.JButton();
        jTextField_numMerkel = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField_frais = new javax.swing.JTextField();
        jPanel_import_export = new javax.swing.JPanel();
        jTextField_jsonFichier = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton_exportJson = new javax.swing.JButton();
        jButton_importJson = new javax.swing.JButton();
        jButton_printAllBlock = new javax.swing.JButton();
        jButton_printBlock = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jTextField_printBlock = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Configue BlockChain");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setModalExclusionType(null);
        setPreferredSize(new java.awt.Dimension(420, 550));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("Difficulté : ");

        jTextField_difficulte.setText("3");
        jTextField_difficulte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_difficulteActionPerformed(evt);
            }
        });

        jTextField_nbDiv.setText("10");
        jTextField_nbDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_nbDivActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setText("Interval division recompence");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("Block maximun :");

        jTextField_nbBlock.setText("1000");
        jTextField_nbBlock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_nbBlockActionPerformed(evt);
            }
        });

        jTextField_nbUser.setText("10");
        jTextField_nbUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_nbUserActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel1.setText("Nombre utilsateur(s) :");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setText("Veuillez entrer les informations suivantes s'il vous plait :");

        jTextField_recompence.setText("50");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("Récompence :");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText(" Afficher block :");

        buttonGroup_print.add(jRadioButton_print_true);
        jRadioButton_print_true.setText("Oui");
        jRadioButton_print_true.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_print_trueActionPerformed(evt);
            }
        });

        buttonGroup_print.add(jRadioButton_print_false);
        jRadioButton_print_false.setSelected(true);
        jRadioButton_print_false.setText("Non");
        jRadioButton_print_false.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_print_falseActionPerformed(evt);
            }
        });

        jButton_start.setBackground(new java.awt.Color(255, 255, 255));
        jButton_start.setText("Start");
        jButton_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_startActionPerformed(evt);
            }
        });

        jButton_verifChain.setBackground(new java.awt.Color(255, 255, 255));
        jButton_verifChain.setText("Verfication Integrité");
        jButton_verifChain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_verifChainActionPerformed(evt);
            }
        });

        jButton_verifMerkel.setBackground(new java.awt.Color(255, 255, 255));
        jButton_verifMerkel.setText("Verification");
        jButton_verifMerkel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_verifMerkelActionPerformed(evt);
            }
        });

        jTextField_numMerkel.setText("0");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("Verification merkel block nᵒ");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel11.setText("Frais de transaction en % :");

        jTextField_frais.setText("5");

        javax.swing.GroupLayout jPanel_configLayout = new javax.swing.GroupLayout(jPanel_config);
        jPanel_config.setLayout(jPanel_configLayout);
        jPanel_configLayout.setHorizontalGroup(
            jPanel_configLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_configLayout.createSequentialGroup()
                .addGroup(jPanel_configLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_configLayout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jButton_start, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_configLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jButton_verifChain, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_configLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel_configLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel_configLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_numMerkel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton_verifMerkel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel_configLayout.createSequentialGroup()
                                .addGroup(jPanel_configLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel_configLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1))
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addGroup(jPanel_configLayout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(51, 51, 51)
                                        .addComponent(jRadioButton_print_true, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel11))
                                .addGroup(jPanel_configLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel_configLayout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(jRadioButton_print_false)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_configLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel_configLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextField_nbUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                                            .addComponent(jTextField_nbBlock, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jTextField_nbDiv, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jTextField_difficulte, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jTextField_recompence, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jTextField_frais))))))))
                .addGap(0, 24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_configLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        jPanel_configLayout.setVerticalGroup(
            jPanel_configLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_configLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_configLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_nbUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_configLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_nbBlock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_configLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField_nbDiv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_configLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_difficulte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_configLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_recompence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel_configLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField_frais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel_configLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jRadioButton_print_true)
                    .addComponent(jRadioButton_print_false, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jButton_start)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_verifChain)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_configLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_numMerkel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_verifMerkel)
                    .addComponent(jLabel6))
                .addGap(48, 48, 48))
        );

        jTabbedPane.addTab("Config", jPanel_config);

        jTextField_jsonFichier.setText("BlockChain.json");

        jLabel9.setText("Fichier :");

        jButton_exportJson.setText("Export");
        jButton_exportJson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_exportJsonActionPerformed(evt);
            }
        });

        jButton_importJson.setText("Import");
        jButton_importJson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_importJsonActionPerformed(evt);
            }
        });

        jButton_printAllBlock.setText("Print all block");
        jButton_printAllBlock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_printAllBlockActionPerformed(evt);
            }
        });

        jButton_printBlock.setText("Print");
        jButton_printBlock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_printBlockActionPerformed(evt);
            }
        });

        jLabel10.setText("Print block nᵒ");

        jTextField_printBlock.setText("0");

        javax.swing.GroupLayout jPanel_import_exportLayout = new javax.swing.GroupLayout(jPanel_import_export);
        jPanel_import_export.setLayout(jPanel_import_exportLayout);
        jPanel_import_exportLayout.setHorizontalGroup(
            jPanel_import_exportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_import_exportLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel_import_exportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel_import_exportLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_printBlock, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_printBlock))
                    .addGroup(jPanel_import_exportLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_import_exportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_import_exportLayout.createSequentialGroup()
                                .addComponent(jButton_importJson, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(128, 128, 128))
                            .addGroup(jPanel_import_exportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextField_jsonFichier, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton_exportJson, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton_printAllBlock, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel_import_exportLayout.setVerticalGroup(
            jPanel_import_exportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_import_exportLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel_import_exportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_jsonFichier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_import_exportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_importJson)
                    .addComponent(jButton_exportJson))
                .addGap(31, 31, 31)
                .addComponent(jButton_printAllBlock)
                .addGap(18, 18, 18)
                .addGroup(jPanel_import_exportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_printBlock)
                    .addComponent(jTextField_printBlock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addContainerGap(282, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Import/Export", jPanel_import_export);

        getContentPane().add(jTabbedPane, java.awt.BorderLayout.PAGE_START);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void jButton_startActionPerformed(java.awt.event.ActionEvent evt) {  
        int nbUser = Integer.parseInt(jTextField_nbUser.getText());
        int nbBlock = Integer.parseInt(jTextField_nbBlock.getText());
        int nbDiv = Integer.parseInt(jTextField_nbDiv.getText());
        int difficulte = Integer.parseInt(jTextField_difficulte.getText());
        int recompence = Integer.parseInt(jTextField_recompence.getText());
        float frais = Float.parseFloat(jTextField_frais.getText());

        chain = new BlockChain(nbUser);

        if (jRadioButton_print_true.isSelected()) chain.setPrint( true );
        if (jRadioButton_print_false.isSelected()) chain.setPrint( false );

        chain.setDifficulte(difficulte);
        chain.setNbBlockDiv(nbDiv);
        chain.setBlockMax(nbBlock);
        chain.setRecompenceBnb(recompence);
        chain.setFee(frais/100);
        
        chain.start();

    }                                             

    private void jRadioButton_print_falseActionPerformed(java.awt.event.ActionEvent evt) {                                                         
        // TODO add your handling code here:
    }                                                        

    private void jRadioButton_print_trueActionPerformed(java.awt.event.ActionEvent evt) {                                                        
        // TODO add your handling code here:
    }                                                       

    private void jTextField_nbUserActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
    }                                                 

    private void jTextField_nbBlockActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:
    }                                                  

    private void jTextField_nbDivActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
    }                                                

    private void jTextField_difficulteActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        // TODO add your handling code here:
    }                                                     

    private void jButton_verifChainActionPerformed(java.awt.event.ActionEvent evt) {        
        if (chain  == null || chain.isEmpty()){
             System.out.println("BlockChain vide");
        }
        else {
            if (chain.verifChain()){
            System.out.println("Integrit� : OK");
            }
            else {
                System.out.println("Integrit� : Compromise");
            }
        }
        
    }                                                  

    private void jButton_verifMerkelActionPerformed(java.awt.event.ActionEvent evt) {    
        if (jTextField_numMerkel.getText().equals("")){
            System.out.println("Case vide");
        }
        else if (chain  == null || chain.isEmpty()){
            System.out.println("BlockChain vide");
        }
        else {
            int numblock = Integer.parseInt(jTextField_numMerkel.getText()); 
            if (chain.getChaine().get(numblock).verifMerkel()){
                System.out.println("Merkel block n� " + numblock + " : OK");
            }
            else {
                System.out.println("Merkel block n� " + numblock + " : Incorrecte");
            }
        }
    }                                                   

    private void jButton_exportJsonActionPerformed(java.awt.event.ActionEvent evt) {       
        BCJsonUtils.BCJsonWriter(chain, jTextField_jsonFichier.getText());
    }                                                  

    private void jButton_importJsonActionPerformed(java.awt.event.ActionEvent evt) {     
       chain = BCJsonUtils.BCJsonReader(jTextField_jsonFichier.getText());
    }                                                  

    private void jButton_printBlockActionPerformed(java.awt.event.ActionEvent evt) {         
        if (jTextField_printBlock.getText().equals("")){
            System.out.println("Case vide");
        }
        else if (chain == null || chain.isEmpty()){
            System.out.println("BlockChain vide");
        }
        else {
        	System.out.println("-------------------------");
            chain.getChaine().get(Integer.parseInt(jTextField_printBlock.getText())).printBlock();
        }
        
        
    }                                                  

    private void jButton_printAllBlockActionPerformed(java.awt.event.ActionEvent evt) {    
        if (chain == null || chain.isEmpty()){
            System.out.println("BlockChain vide");
        }
        else {
            for (Block blk : chain.getChaine())
		{
			blk.printBlock();
		}
        }           
    }                                                     

    /**
     * @param args the command line arguments
     */
    	

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton_exportJson;
    private javax.swing.JButton jButton_importJson;
    private javax.swing.JButton jButton_printAllBlock;
    private javax.swing.JButton jButton_printBlock;
    private javax.swing.JButton jButton_start;
    private javax.swing.JButton jButton_verifChain;
    private javax.swing.JButton jButton_verifMerkel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel_config;
    private javax.swing.JPanel jPanel_import_export;
    private javax.swing.JRadioButton jRadioButton_print_false;
    private javax.swing.JRadioButton jRadioButton_print_true;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTextField jTextField_difficulte;
    private javax.swing.JTextField jTextField_jsonFichier;
    private javax.swing.JTextField jTextField_nbBlock;
    private javax.swing.JTextField jTextField_nbDiv;
    private javax.swing.JTextField jTextField_nbUser;
    private javax.swing.JTextField jTextField_numMerkel;
    private javax.swing.JTextField jTextField_printBlock;
    private javax.swing.JTextField jTextField_recompence;
    private javax.swing.JTextField jTextField_frais;
    // End of variables declaration                   
    private BlockChain chain;
    private void getTaxte() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
